In [5]:
import pandas as pd
import os
import tempfile

# Link do pliku
url = 'https://raw.githubusercontent.com/BigDataGrupaDruga/BigDataDiamonds/refs/heads/main/CleaningData/diamonds_noisy.csv'

dataset = pd.read_csv(url)

# Zapisanie danych do tymczasowego pliku
with tempfile.NamedTemporaryFile(delete=False, mode='w', suffix='.csv') as tmp_file:
    dataset.to_csv(tmp_file.name, index=False)
    tmp_file_path = tmp_file.name

# Wczytanie danych jako zwykły tekst
with open(tmp_file_path, 'r') as file:
    lines = file.readlines()

# Przetworzenie danych
data = []
for line in lines:
    # Usunięcie niepotrzebnych znaków, takich jak `'``
    line = line.replace("'`", '')
    
    # Naprawienie pisowni
    line = line.replace("Go0d", "Good").replace("Pre_AEiu_AE", "Premium")
    
    # Podział na kolumny
    columns = line.strip().split(',')
    data.append(columns)

# Tworzenie DataFrame
df = pd.DataFrame(data)

# Usunięcie tymczasowego pliku
os.unlink(tmp_file_path)

In [7]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10
0,"""","""""carat""""","""""cut""""","""""color""""","""""clarity""""","""""depth""""","""""table""""","""""price""""","""""x""""","""""y""""","""""z"""""""
1,"""1",0.23,"""""Ideal""""","""""E""""","""""SI2""""",61.5,55,326,3.95,3.98,"2.43"""
2,"""2",0.21,"""""Premium""""","""""E""""","""""SI1""""",59.8,61,326,3.89,3.84,"2.31"""
3,"""3",0.23,"""""Good""""","""""E""""","vS1""""",56.9,65,327,4.05,4.07,"2.31"""
4,"""4",0.29,"""""Premium""""","""""I""""","vS2""""",62.4,58,334,4.2,4.23,"2.63"""

In [ ]:
#Zapisanie pliku za pomocą metody ".to_csv"